### ISSUE TITLE
Dynamic binding

### ISSUE THREAD

**Issue by madorin** [perevoznyk/swelio-delphi#1]
Hello, Serhiy,

Can you add please "delayed" flag for dll functions in Delphi/SwelioEngine.pas?
It is supported starting with Delphi 2010. Or at least to be controlled by a compiler define switch.
There are cases when you don't need explicitelly eID card functionality but dll is always loaded on project launch.

Thanks!

**Comment by perevoznyk** [comment]
Done

**Comment by madorin** [comment]
Many thanks!

**Comment by madorin** [comment]
Seems for "external SwelioLib name '*" bunch not yet ;)

**Comment by perevoznyk** [comment]
You are right, I made an update for it
