### ISSUE TITLE
Old Belgian eID not valid after reading new eID

### ISSUE THREAD

**Issue by stbor-tilroy** [perevoznyk/swelio-delphi#2]
Hi Serhiy,

I run into some problems with the new dll and old Belgian eID's.
It seems to work fine until you insert an old eID after a new eID, the IsEIDCard flag returns false in that case.
After pulling the card out and inserting it again the data is read.

New eID is never a problem, it is always reading correctly after inserting it.

Thanks for looking into this.
If you need anymore info let me know.

Thx,
Stefan

**Comment by perevoznyk** [comment]
I just did the test with different id cards v1.7 and v1.8 and IsEID reported correctly the type of the card in all combinations. I used dll version 1.18.6 (which is available in the repo) and DemoReader project (just updated it as well). Could you repeat the test using this version, please? Do you see in the log the message that the card is inserted / removed every time ?

**Comment by stbor-tilroy** [comment]
Thanks for the quick response.

In the demo app it appears to work correctly.
The code between the samlpe and our app is very similar but I'm going through our code again to see if I can find a difference that is responsible for this behavior.

Thx,
Stefan

**Comment by stbor-tilroy** [comment]
Hi
After some more testing it seems like a pc/driver/card-reader related issue.
I could only reproduce the issue on 2 pc's (1 always an issue, the other more randomly), all others(4) worked as expected.

Stefan
