### ISSUE TITLE
Unicode version of SwelioEngine functions raise errors

### ISSUE THREAD

**Issue by devgijbels** [perevoznyk/swelio-delphi#3]
Hi, 

We are trying to implement EID reading functionality in our program using the Swelio-delphi Engine. We built the EID Demo in the Samples directory and tried to run it. This failed on a D2010 environment. After using all <functionname>A -variants of the failing functions (and changing the code accordingly), the functions worked as expected. 

<img width="783" alt="2022-02-21 15_13_51-DemoReader - Delphi 2010 - frm_main  Stopped - Thread 18056" src="https://user-images.githubusercontent.com/99254586/154979602-304d5fdf-7d06-463e-8762-7a308bf5291d.png">

**Comment by perevoznyk** [comment]
Sorry, but I can't reproduce this bug

**Comment by devgijbels** [comment]
> Sorry, but I can't reproduce this bug

Hi Serhiy, 

First of all, thanks for your reply. Could I provide you with extra information? I forked your project and made the necessary changes in my repository. The changes in my code are marked with // AG 07/03/2022. 
I uploaded my version info, maybe this could be helpful to you:
[version_info_D2010.txt](https://github.com/perevoznyk/swelio-delphi/files/8200224/version_info_D2010.txt)
Please let me know if you need anything else to investigate this issue. 

Best regards,
Annelies Gijbels
