### ISSUE TITLE
problem with ReadAddressEx

### ISSUE THREAD

**Issue by bobwalbers** [perevoznyk/swelio-delphi#4]
Hello

We are testing the library on a system with multiple cardreaders connected.
In the sample code frm_main.pas , we have therefore replaced the calls:

`isEIDcard` 
by 
`IsEIDCardEx(aReaderNumber)`

`ReadIdentity(@Identity) `
by 
`ReadIdentityEx(aReaderNumber, @Identity)`

`ReadAddress(@Address) `
by 
`ReadAddressEx(aReaderNumber, @Address);`

`ReadPhoto(@Pic) `
by 
`ReadPhotoEx(aReaderNumber, @Pic)`

This works OK except for `ReadAddressEx` where null values are returned in Address when aReaderNumber is greater than 0.

**Comment by perevoznyk** [comment]
Fixed in v1.18.19 Please update to the last version
