### ISSUE TITLE
Swelioengine.pas function DocumentTypeToString

### ISSUE THREAD

**Issue by VerbovenBerg** [perevoznyk/swelio-delphi#5]
Dear Mr. Perevoznyk,

We use the function DocumentTypeToString to display the documenttype in our software.
Clients frequently get the message 'unknown card'.
We just found that the function recognizes 18 cardtypes.
But there must be some types missing.
Is this something that can be fixed?

Thanks.

**Comment by perevoznyk** [comment]
Hello,

I fixed this issue in v1.18.19. Added new card types and also changed the message in case if the card type is still unknown. Now it will also specify which type is unknown. if it happens again, please contact me and I will add new missing types of the cards to DocumentTypeToString function
