### ISSUE TITLE
Reader callback in constant readers list changed loop.

### ISSUE THREAD

**Issue by Dionysius1984** [perevoznyk/swelio-delphi#8]
Hello,

I am having the issue with your demo reader program for Delphi that this is in a constant readers list changed loop.
I do have to say that I am using Delphi 5. This is used in house for all our development for years which is why this has not been updated before you ask why we are still on that version. 

I have been reading the issues for the non delphi Swelio repository and something was mentioned about Sd card readers being one of the issues. If I disable this SD Card reader in my system then the demo reader program stops with it's loop. The strange thing though is that the demo reader program has only detected 1 card reader. I made an adjustment to use the GetReadersCount to update the found readers since I was curious if another reader was found. 

I have made sure too use the latest version of the delphi repository and also the most up to date Swelio32.dll of 18-9-2023 (the one in the delphi repository is a 2022 version)

Could you help me with this? or is their another way to handle this then disabling a device?

**Comment by perevoznyk** [comment]
This issue is fixed in v1.18.30
Additionally 2 procedures added IgnoreHardwareEvents and IgnoreServiceEvents. By defaults this kind of events is ignored now, but you can switch it on by using new procedures, if necessary
